version: '3'

services: 
  postgres:
    image: postgres:12.2-alpine
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local